### PR TITLE
Update .gitignore to ignore .idea

### PR DESCRIPTION
**Pull request by SubhrajyotiSen**

### CODE REVIEW

**Review by abunur — APPROVED** [review]

**Comment by gabrielaa03** [comment]
@SubhrajyotiSen @abunur Okay, so I'm not sure if this was the best idea. We will have a lot of conflicts now when merging the edition branch to the ones already updated. It would be better if you let me do this for each chapter, or every author could paste .gitignore stuff once updating the chapter. Just please, don't merge changes by yourself since there is a bunch of already updated chapters. Let me handle that.

**Comment by SubhrajyotiSen** [comment]
@gabrielaa03 I meant for this PR to be reference to copy the .gitignore changes from. Would it be possible to reset the HEAD and force push for the editions/2.0 branch?

**Comment by gabrielaa03** [comment]
@SubhrajyotiSen Let's leave it as a reference, I'll update all branches. I don't want to mess up with the edition branch. Thanks, though!

**Comment by gabrielaa03** [comment]
Actually, I'll handle it somehow after the day job, don't worry about it. Since we didn't push anything to the edition branch since this PR, I'll probably reset it :]

**Comment by abunur** [comment]
Sorry if I messed things up by merging. One of the hazards of working late…

Fuad Kamal
Anaara LLC
www.anaara.com
(435) 799-5904 (m)
***@***.***Ronin
author, The Kotlin Book: http://thekotlinbook.com
co-author of Android Apprentice, Android App Distribution, and Saving Data on Android
RayWenderlich.com Team member, https://www.raywenderlich.com/u/abunur
behance: https://www.behance.net/fuadkamal
linkedIn: linkedin.com/in/anaara
photography: https://fuadkamal.org | https://www.instagram.com/flexronin/

**Pull request merged**
